/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.sql.ResultSet;
import kode.koneksi;
import kode.mobil;
import kode.pelanggan;
import kode.peminjaman;
import kode.pegawai;

/**
 *
 * @author LENOVO
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        insertPegawaiPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idPegawaiField5 = new javax.swing.JTextField();
        namaField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPegawaiField5 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cpPegawaiField5 = new javax.swing.JTextField();
        usernameField5 = new javax.swing.JTextField();
        passwordField5 = new javax.swing.JTextField();
        insertBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        dataPegawaiPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idPegawaiSearchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        idPegawaiField1 = new javax.swing.JTextField();
        namaPegawaiField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPegawaiField1 = new javax.swing.JTextArea();
        cpPegawaiField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        passwordField1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        kodeField1 = new javax.swing.JTextField();
        insertMobilPanel = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        idMobilField6 = new javax.swing.JTextField();
        jenisField6 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        sewaField6 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        stokField6 = new javax.swing.JTextField();
        insertBtn1 = new javax.swing.JButton();
        resetBtn1 = new javax.swing.JButton();
        dataMobilPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        idMobilSearchField1 = new javax.swing.JTextField();
        searchBtn1 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        updateBtn1 = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        idMobilField7 = new javax.swing.JTextField();
        jenisField7 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        sewaField7 = new javax.swing.JTextField();
        stokField7 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminPanel.setBackground(new java.awt.Color(255, 255, 153));
        adminPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Welcome To Administrator");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(31, 31, 31))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Admin", adminPanel);

        insertPegawaiPanel.setBackground(new java.awt.Color(255, 255, 153));
        insertPegawaiPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Insert Data Admin");

        jLabel10.setText("Id Admin : ");

        jLabel11.setText("Nama :");

        jLabel13.setText("Alamat :");

        alamatPegawaiField5.setColumns(20);
        alamatPegawaiField5.setRows(5);
        jScrollPane1.setViewportView(alamatPegawaiField5);

        jLabel12.setText("Contact Person :");

        jLabel43.setText("Username :");

        jLabel44.setText("Password :");

        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertPegawaiPanelLayout = new javax.swing.GroupLayout(insertPegawaiPanel);
        insertPegawaiPanel.setLayout(insertPegawaiPanelLayout);
        insertPegawaiPanelLayout.setHorizontalGroup(
            insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                        .addComponent(insertBtn)
                        .addGap(80, 80, 80)
                        .addComponent(resetBtn))
                    .addComponent(cpPegawaiField5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                            .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(namaField5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertPegawaiPanelLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idPegawaiField5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel8)))
                    .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                        .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addGap(252, 252, 252)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        insertPegawaiPanelLayout.setVerticalGroup(
            insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPegawaiPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idPegawaiField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namaField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cpPegawaiField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(usernameField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(passwordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(insertPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(insertBtn))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("insert admin", insertPegawaiPanel);

        dataPegawaiPanel.setBackground(new java.awt.Color(255, 255, 153));
        dataPegawaiPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Search Data Admin");

        jLabel15.setText("Id Admin : ");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Result");

        jLabel17.setText("Id Admin : ");

        jLabel18.setText("Nama :");

        jLabel19.setText("Alamat :");

        alamatPegawaiField1.setColumns(20);
        alamatPegawaiField1.setRows(5);
        jScrollPane2.setViewportView(alamatPegawaiField1);

        jLabel20.setText("Contact Person :");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel45.setText("Username :");

        jLabel46.setText("Password : ");

        jLabel47.setText("Kode : ");

        javax.swing.GroupLayout dataPegawaiPanelLayout = new javax.swing.GroupLayout(dataPegawaiPanel);
        dataPegawaiPanel.setLayout(dataPegawaiPanelLayout);
        dataPegawaiPanelLayout.setHorizontalGroup(
            dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(updateBtn)
                                        .addGap(90, 90, 90)
                                        .addComponent(deleteBtn))
                                    .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(namaPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPegawaiPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(idPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel45)
                                                .addGap(18, 18, 18)
                                                .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel46)
                                                .addGap(18, 18, 18)
                                                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel47)
                                                .addGap(18, 18, 18)
                                                .addComponent(kodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(cpPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idPegawaiSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        dataPegawaiPanelLayout.setVerticalGroup(
            dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPegawaiPanelLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(idPegawaiSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(15, 15, 15)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(idPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(namaPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpPegawaiField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("data admin", dataPegawaiPanel);

        insertMobilPanel.setBackground(new java.awt.Color(255, 255, 153));
        insertMobilPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel48.setText("Insert Data Video");

        jLabel49.setText("Id Video : ");

        jLabel50.setText("Jenis :");

        jLabel52.setText("Sewa :");

        jLabel53.setText("Stok :");

        insertBtn1.setText("Insert");
        insertBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtn1ActionPerformed(evt);
            }
        });

        resetBtn1.setText("Reset");
        resetBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertMobilPanelLayout = new javax.swing.GroupLayout(insertMobilPanel);
        insertMobilPanel.setLayout(insertMobilPanelLayout);
        insertMobilPanelLayout.setHorizontalGroup(
            insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertMobilPanelLayout.createSequentialGroup()
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(insertMobilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(sewaField6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertMobilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(252, 252, 252))
                    .addGroup(insertMobilPanelLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(jenisField6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertMobilPanelLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idMobilField6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(insertMobilPanelLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLabel48)))
                    .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(insertMobilPanelLayout.createSequentialGroup()
                            .addComponent(insertBtn1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetBtn1))
                        .addComponent(stokField6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        insertMobilPanelLayout.setVerticalGroup(
            insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertMobilPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel48)
                .addGap(27, 27, 27)
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(idMobilField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jenisField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(sewaField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(stokField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn1)
                    .addComponent(resetBtn1))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("insert Video", insertMobilPanel);

        dataMobilPanel.setBackground(new java.awt.Color(255, 255, 153));
        dataMobilPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Search Video");

        jLabel51.setText("Id Video : ");

        searchBtn1.setText("Search");
        searchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn1ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel54.setText("Result");

        updateBtn1.setText("Update");
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });

        deleteBtn1.setText("Delete");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        jLabel55.setText("Id Video : ");

        jLabel56.setText("Jenis :");

        jLabel57.setText("Sewa :");

        jLabel58.setText("Stok :");

        javax.swing.GroupLayout dataMobilPanelLayout = new javax.swing.GroupLayout(dataMobilPanel);
        dataMobilPanel.setLayout(dataMobilPanelLayout);
        dataMobilPanelLayout.setHorizontalGroup(
            dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMobilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataMobilPanelLayout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(18, 18, 18)
                                .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel57)
                                        .addGap(18, 18, 18)
                                        .addComponent(sewaField7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel58)
                                        .addGap(252, 252, 252))
                                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addGap(18, 18, 18)
                                        .addComponent(jenisField7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idMobilField7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                            .addComponent(updateBtn1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteBtn1))
                                        .addComponent(stokField7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(dataMobilPanelLayout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idMobilSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn1))))
                    .addComponent(jLabel21))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        dataMobilPanelLayout.setVerticalGroup(
            dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMobilPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(idMobilSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn1))
                .addGap(18, 18, 18)
                .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addGroup(dataMobilPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(idMobilField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(jenisField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(sewaField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(stokField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(dataMobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn1)
                    .addComponent(updateBtn1))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Video", dataMobilPanel);

        reportPanel.setBackground(new java.awt.Color(255, 255, 153));
        reportPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Pelanggan", "Mobil", "Petugas", "Tgl Mulai", "Tgl Selesai", "Sewa", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Report", reportPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        log.dispose();
        javax.swing.JOptionPane.showMessageDialog(null, "Logout Success");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;

        try {
            rs = kon.getData("select * from pelanggan where id_pelanggan = '" + idPegawaiSearchField.getText() + "'");
            while(rs.next()){
                idPegawaiField1.setText(rs.getString("id_pegawai"));
                namaPegawaiField1.setText(rs.getString("nama"));
                alamatPegawaiField1.setText(rs.getString("alamat"));
                cpPegawaiField1.setText(rs.getString("cp"));
                usernameField1.setText(rs.getString("username"));
                passwordField1.setText(rs.getString("password"));

                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");

                idPegawaiField1.setText(null);
                namaPegawaiField1.setEnabled(true);
                alamatPegawaiField1.setEnabled(true);
                cpPegawaiField1.setEnabled(true);
                usernameField1.setEnabled(true);
                passwordField1.setEnabled(true);
                kodeField1.setEnabled(true);

                // Enabling buttons for update and delete
                updateBtn.setEnabled(true);
                deleteBtn.setEnabled(true);

            }
            rs.close();
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        idPegawaiField1.setEnabled(false);
        namaPegawaiField1.setEnabled(false);
        alamatPegawaiField1.setEnabled(false);
        cpPegawaiField1.setEnabled(false);
        usernameField1.setEnabled(false);
        passwordField1.setEnabled(false);
        kodeField1.setEnabled(false);
        
        pegawai peg = new pegawai();
        peg.setId(idPegawaiField1.getText());
        peg.setNama(namaPegawaiField1.getText());
        peg.setAlamat(alamatPegawaiField1.getText());
        peg.setCp(cpPegawaiField1.getText());
        peg.setUsername(usernameField1.getText());
        peg.setPassword(passwordField1.getText());
        peg.setKode(kodeField1.getText());
        peg.updatePegawai();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        idPegawaiField1.setEnabled(false);
        namaPegawaiField1.setEnabled(false);
        alamatPegawaiField1.setEnabled(false);
        cpPegawaiField1.setEnabled(false);
        usernameField1.setEnabled(false);
        passwordField1.setEnabled(false);
        kodeField1.setEnabled(false);
        pegawai peg = new pegawai();
        peg.setId(idPegawaiField1.getText());
        peg.setNama(namaPegawaiField1.getText());
        peg.setAlamat(alamatPegawaiField1.getText());
        peg.setCp(cpPegawaiField1.getText());
        peg.setUsername(usernameField1.getText());
        peg.setPassword(passwordField1.getText());
        peg.setKode(kodeField1.getText());
        peg.deletePegawai();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
        
        idPegawaiField1.setText(null);
        namaPegawaiField1.setText(null);
        alamatPegawaiField1.setText(null);
        cpPegawaiField1.setText(null);
        usernameField1.setText(null);
        passwordField1.setText(null);
        kodeField1.setText(null);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void insertBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtn1ActionPerformed
        // TODO add your handling code here:
        mobil mob = new mobil();
        mob.setId (idMobilField6.getText());
        mob.setJenis (jenisField6.getText());
        mob.setSewa (sewaField6.getText());
        mob.setStok(stokField6.getText());
        mob.insertMobil();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
    }//GEN-LAST:event_insertBtn1ActionPerformed

    private void resetBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtn1ActionPerformed
        // TODO add your handling code here:
        idMobilField6.setText(null) ;
        jenisField6.setText(null);
        sewaField6.setText(null);
    }//GEN-LAST:event_resetBtn1ActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        // TODO add your handling code here:
        idMobilField6.setEnabled(false);
        jenisField6.setEnabled(false);
        sewaField6.setEnabled(false);
        stokField6.setEnabled(false);
        
        mobil mob = new mobil();
        mob.setId(idMobilField6.getText());
        mob.setJenis(jenisField6.getText());
        mob.setSewa(sewaField6.getText());
        mob.setStok(stokField6.getText());
        mob.deleteMobil();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
        
        idMobilField6.setText(null);
        jenisField6.setText(null);
        sewaField6.setText(null);
        stokField6.setText(null);
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtn1ActionPerformed

    private void searchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn1ActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;

        try {
            rs = kon.getData("SELECT * FROM mobil WHERE id_mobil = '" + idMobilSearchField1.getText() + "'");

            while (rs.next()) {
                idMobilField7.setText(rs.getString("id_mobil"));
                jenisField7.setText(rs.getString("jenis"));
                sewaField7.setText(rs.getString("sewa"));
                stokField7.setText(rs.getString("stok"));

                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");

                idMobilField7.setText(null);
                jenisField7.setEnabled(true);
                sewaField7.setEnabled(true);
                stokField7.setEnabled(true);
                updateBtn1.setEnabled(true);
                deleteBtn1.setEnabled(true);
            }
            rs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        mobil mob = new mobil();
        mob.setId(idMobilField7.getText());
        mob.setJenis(jenisField7.getText());
        mob.setSewa(sewaField7.getText());
        mob.setStok(stokField7.getText());
        mob.updateMobil();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");

    }//GEN-LAST:event_searchBtn1ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;
        int i = 0;
        
        try {
            rs = kon.getData("SELECT * FROM peminjaman");

            while (rs.next()) {
                jTable1.setValueAt(rs.getString("id_peminjaman"), i, 0);
                jTable1.setValueAt(rs.getString("id_pelanggan"), i, 1);
                jTable1.setValueAt(rs.getString("id_mobil"), i, 2);
                jTable1.setValueAt(rs.getString("id_petugas"), i, 3);
                jTable1.setValueAt(rs.getString("tgl_pinjam"), i, 4);
                jTable1.setValueAt(rs.getString("tgl_hrs_kembali"), i, 5);
                jTable1.setValueAt(rs.getString("biaya"), i, 6);
                jTable1.setValueAt(rs.getString("denda"), i, 7);
                i++;
            }
            rs.close();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        pegawai peg = new pegawai();

        peg.setId(idPegawaiField5.getText());
        peg.setNama(namaField5.getText());
        peg.setAlamat(alamatPegawaiField5.getText());
        peg.setCp(cpPegawaiField5.getText());
        peg.setUsername(usernameField5.getText());
        peg.setPassword(passwordField5.getText());

        peg.insertPegawai();

        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");

        idPegawaiField5.setText(null);
        namaField5.setText(null);
        alamatPegawaiField5.setText(null);
        cpPegawaiField5.setText(null);
        usernameField5.setText(null);
        passwordField5.setText(null);
    }//GEN-LAST:event_insertBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        idPegawaiField5.setText(null);
        namaField5.setText(null);
        alamatPegawaiField5.setText(null);
        cpPegawaiField5.setText(null);
        usernameField5.setText(null);
        passwordField5.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JTextArea alamatPegawaiField1;
    private javax.swing.JTextArea alamatPegawaiField5;
    private javax.swing.JTextField cpPegawaiField1;
    private javax.swing.JTextField cpPegawaiField5;
    private javax.swing.JPanel dataMobilPanel;
    private javax.swing.JPanel dataPegawaiPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JTextField idMobilField6;
    private javax.swing.JTextField idMobilField7;
    private javax.swing.JTextField idMobilSearchField1;
    private javax.swing.JTextField idPegawaiField1;
    private javax.swing.JTextField idPegawaiField5;
    private javax.swing.JTextField idPegawaiSearchField;
    private javax.swing.JButton insertBtn;
    private javax.swing.JButton insertBtn1;
    private javax.swing.JPanel insertMobilPanel;
    private javax.swing.JPanel insertPegawaiPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jenisField6;
    private javax.swing.JTextField jenisField7;
    private javax.swing.JTextField kodeField1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField namaField5;
    private javax.swing.JTextField namaPegawaiField1;
    private javax.swing.JTextField passwordField1;
    private javax.swing.JTextField passwordField5;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton resetBtn1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JTextField sewaField6;
    private javax.swing.JTextField sewaField7;
    private javax.swing.JTextField stokField6;
    private javax.swing.JTextField stokField7;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateBtn1;
    private javax.swing.JTextField usernameField1;
    private javax.swing.JTextField usernameField5;
    // End of variables declaration//GEN-END:variables
}
