/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.sql.ResultSet;
import kode.koneksi;
import kode.pelanggan;
import kode.peminjaman;

/**
 *
 * @author LENOVO
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        userPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inputPelangganPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idPelangganField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        namaPelangganField = new javax.swing.JTextField();
        cpPelangganField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPelangganField = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        dataPelangganPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idPelangganSearchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        idPelangganField1 = new javax.swing.JTextField();
        namaPelangganField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPelangganField1 = new javax.swing.JTextArea();
        cpPelangganField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        mobilPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        peminjamanPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        generatePeminjamanBtn = new javax.swing.JButton();
        idPegawaiField = new javax.swing.JTextField();
        idPeminjamanField = new javax.swing.JTextField();
        idPelangganField2 = new javax.swing.JTextField();
        lamaField = new javax.swing.JTextField();
        jenisMobilComboBox = new javax.swing.JComboBox<>();
        tanggalComboBox = new javax.swing.JComboBox<>();
        bulanComboBox = new javax.swing.JComboBox<>();
        tahunField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        sewaField = new javax.swing.JTextField();
        totalSewaField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tahunField1 = new javax.swing.JTextField();
        cancelPeminjamanBtn = new javax.swing.JButton();
        savePeminjamanBtn = new javax.swing.JButton();
        pengembalianPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        idPeminjamanField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        idPelangganField3 = new javax.swing.JTextField();
        idMobilField3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tglPinjamField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        lamaPinjamField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        biayaSewaField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tglKembaliField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        telatField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        dendaField = new javax.swing.JTextField();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userPanel.setBackground(new java.awt.Color(255, 255, 153));
        userPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Welcome To User");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(31, 31, 31))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("tab1", userPanel);

        inputPelangganPanel.setBackground(new java.awt.Color(255, 255, 153));
        inputPelangganPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Input Data Pelanggan");

        jLabel10.setText("Id Pelanggan : ");

        jLabel11.setText("Nama :");

        jLabel12.setText("Contact Person :");

        jLabel13.setText("Alamat :");

        alamatPelangganField.setColumns(20);
        alamatPelangganField.setRows(5);
        jScrollPane1.setViewportView(alamatPelangganField);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPelangganPanelLayout = new javax.swing.GroupLayout(inputPelangganPanel);
        inputPelangganPanel.setLayout(inputPelangganPanelLayout);
        inputPelangganPanelLayout.setHorizontalGroup(
            inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPelangganPanelLayout.createSequentialGroup()
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inputPelangganPanelLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(18, 18, 18)
                            .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(namaPelangganField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPelangganPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(inputPelangganPanelLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(jLabel8))
                        .addGroup(inputPelangganPanelLayout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(saveBtn)
                            .addGap(76, 76, 76)
                            .addComponent(cancelBtn))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        inputPelangganPanelLayout.setVerticalGroup(
            inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPelangganPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(namaPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cpPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(inputPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", inputPelangganPanel);

        dataPelangganPanel.setBackground(new java.awt.Color(255, 255, 153));
        dataPelangganPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Search Data Pelanggan");

        jLabel15.setText("Id Pelanggan : ");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Result");

        jLabel17.setText("Id Pelanggan : ");

        jLabel18.setText("Nama :");

        jLabel19.setText("Alamat :");

        alamatPelangganField1.setColumns(20);
        alamatPelangganField1.setRows(5);
        jScrollPane2.setViewportView(alamatPelangganField1);

        jLabel20.setText("Contact Person :");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPelangganPanelLayout = new javax.swing.GroupLayout(dataPelangganPanel);
        dataPelangganPanel.setLayout(dataPelangganPanelLayout);
        dataPelangganPanelLayout.setHorizontalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idPelangganSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn))))
                    .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                                    .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel20))
                                    .addGap(18, 18, 18)
                                    .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(namaPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPelangganPanelLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(idPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(updateBtn)
                        .addGap(73, 73, 73)
                        .addComponent(deleteBtn)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        dataPelangganPanelLayout.setVerticalGroup(
            dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPelangganPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(idPelangganSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(idPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(namaPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cpPelangganField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", dataPelangganPanel);

        mobilPanel.setBackground(new java.awt.Color(255, 255, 153));
        mobilPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Data Mobil");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Jenis", "Sewa", "Stok"
            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout mobilPanelLayout = new javax.swing.GroupLayout(mobilPanel);
        mobilPanel.setLayout(mobilPanelLayout);
        mobilPanelLayout.setHorizontalGroup(
            mobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobilPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel21)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(mobilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        mobilPanelLayout.setVerticalGroup(
            mobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobilPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", mobilPanel);

        peminjamanPanel.setBackground(new java.awt.Color(255, 255, 153));
        peminjamanPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText("Transaksi Peminjaman");

        jLabel23.setText("Id Pegawai                 : ");

        jLabel24.setText("Id Peminjaman          : ");

        jLabel25.setText("Id Pelanggan             : ");

        jLabel26.setText("Jenis Mobil                :");

        jLabel27.setText("Tanggal Peminjaman : ");

        jLabel28.setText("Lama Peminjaman     : ");

        generatePeminjamanBtn.setText("Generate");
        generatePeminjamanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePeminjamanBtnActionPerformed(evt);
            }
        });

        idPeminjamanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeminjamanFieldActionPerformed(evt);
            }
        });

        idPelangganField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganField2ActionPerformed(evt);
            }
        });

        tahunField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunFieldActionPerformed(evt);
            }
        });

        jLabel29.setText("Biaya Sewa                : ");

        sewaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaFieldActionPerformed(evt);
            }
        });

        jLabel30.setText("Total Sewa                :");

        jLabel31.setText("Tanggal Kembali       :");

        tahunField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunField1ActionPerformed(evt);
            }
        });

        cancelPeminjamanBtn.setText("Cancel");

        savePeminjamanBtn.setText("Save");
        savePeminjamanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePeminjamanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout peminjamanPanelLayout = new javax.swing.GroupLayout(peminjamanPanel);
        peminjamanPanel.setLayout(peminjamanPanelLayout);
        peminjamanPanelLayout.setHorizontalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, peminjamanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jenisMobilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, peminjamanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel22))
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPelangganField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peminjamanPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(peminjamanPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tahunField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peminjamanPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peminjamanPanelLayout.createSequentialGroup()
                        .addComponent(generatePeminjamanBtn)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peminjamanPanelLayout.createSequentialGroup()
                        .addComponent(savePeminjamanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelPeminjamanBtn)
                        .addGap(16, 16, 16))))
        );
        peminjamanPanelLayout.setVerticalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(idPegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(idPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(idPelangganField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jenisMobilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tanggalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generatePeminjamanBtn)
                .addGap(18, 18, 18)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(sewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(totalSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tahunField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelPeminjamanBtn)
                    .addComponent(savePeminjamanBtn))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab5", peminjamanPanel);

        pengembalianPanel.setBackground(new java.awt.Color(255, 255, 153));
        pengembalianPanel.setPreferredSize(new java.awt.Dimension(450, 440));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("Search Data Transaksi");

        jLabel33.setText("Id Peminjaman : ");

        idPeminjamanField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeminjamanField1ActionPerformed(evt);
            }
        });

        jButton1.setText("SearchBtn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("Transaksi Pengembalian");

        jLabel35.setText("Id Pelanggan :");

        jLabel36.setText("Id Mobil :");

        jLabel37.setText("Tanggal Pinjam :");

        jLabel38.setText("Lama Pinjam :");

        jLabel39.setText("Biaya Sewa :");

        jLabel40.setText("Tanggal Kembali :");

        jLabel41.setText("Telat : ");

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel42.setText("Denda : ");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pengembalianPanelLayout = new javax.swing.GroupLayout(pengembalianPanel);
        pengembalianPanel.setLayout(pengembalianPanelLayout);
        pengembalianPanelLayout.setHorizontalGroup(
            pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pengembalianPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel32))
                    .addGroup(pengembalianPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idPeminjamanField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel34)
                            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idPelangganField3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idMobilField3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(biayaSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pengembalianPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lamaPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tglPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telatField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)
                                    .addGroup(pengembalianPanelLayout.createSequentialGroup()
                                        .addComponent(dendaField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Save)))))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pengembalianPanelLayout.setVerticalGroup(
            pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengembalianPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPeminjamanField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(idPelangganField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(idMobilField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tglPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lamaPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(biayaSewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tglKembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(telatField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(dendaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save))
                .addGap(11, 11, 11))
        );

        jTabbedPane1.addTab("tab6", pengembalianPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login log = new Login(); 
        log.setVisible(true); 
        dispose(); 
        javax.swing.JOptionPane.showMessageDialog(null, "Logout Success");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        pelanggan pel = new pelanggan();
        pel.setId(idPelangganField.getText());
        pel.setNama(namaPelangganField.getText());
        pel.setAlamat(alamatPelangganField.getText());
        pel.setCp(cpPelangganField.getText());

        pel.insertPelanggan();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        idPelangganField.setText("");
        namaPelangganField.setText("");
        alamatPelangganField.setText("");
        cpPelangganField.setText("");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;

        try {
            rs = kon.getData("select * from pelanggan where id_pelanggan = '" + idPelangganSearchField.getText() + "'");
            while(rs.next()){
                idPelangganField1.setText(rs.getString("id_pelanggan"));
                namaPelangganField1.setText(rs.getString("nama"));
                alamatPelangganField1.setText(rs.getString("alamat"));
                cpPelangganField1.setText(rs.getString("cp"));
                javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                idPelangganSearchField.setText(null);
                namaPelangganField1.setEnabled(true);
                alamatPelangganField1.setEnabled(true);
                cpPelangganField1.setEnabled(true);
                updateBtn.setEnabled(true);
                deleteBtn.setEnabled(true);
            }
            rs.close();
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        idPelangganField1.setEnabled(false);
        namaPelangganField1.setEnabled(false);
        alamatPelangganField1.setEnabled(false);
        cpPelangganField1.setEnabled(false);
        pelanggan pel = new pelanggan();
        pel.setId(idPelangganField1.getText());
        pel.setNama(namaPelangganField1.getText());
        pel.setAlamat(alamatPelangganField1.getText());
        pel.setCp(cpPelangganField1.getText());
        pel.updatePelanggan();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        idPelangganField1.setEnabled(false);
        namaPelangganField1.setEnabled(false);
        alamatPelangganField1.setEnabled(false);
        cpPelangganField1.setEnabled(false);
        pelanggan pel = new pelanggan();
        pel.setId(idPelangganField1.getText());
        pel.setNama(namaPelangganField1.getText());
        pel.setAlamat(alamatPelangganField1.getText());
        pel.setCp(cpPelangganField1.getText());
        pel.deletePelanggan();
        javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
        idPelangganField1.setText(null);
        namaPelangganField1.setText(null);
        alamatPelangganField1.setText(null);
        cpPelangganField1.setText(null);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;
        int i = 0;
        try {
            rs= kon.getData("select * from mobil");
            while (rs.next()){
                jTable1.setValueAt(rs.getString("id_mobil"), i, 0);
                jTable1.setValueAt(rs.getString("jenis"), i, 1);
                jTable1.setValueAt(rs.getString("sewa"), i, 2);
                jTable1.setValueAt(rs.getString("stok"), i, 3);
                i++;
            }
            rs.close();
        } catch(Exception e){

        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void generatePeminjamanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePeminjamanBtnActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;
        try {
            rs = kon.getData("select * from mobil where id_mobil = '" + jenisMobilComboBox.getSelectedItem() + "'");
            while(rs.next()){
                sewaField.setText(rs.getString("sewa"));
                int k, l, m, n, o;
                k = Integer.valueOf(lamaField.getText()).intValue();
                l = Integer.valueOf("" + tanggalComboBox.getSelectedItem()).intValue();
                n = Integer.valueOf(sewaField.getText()).intValue();
                m = k + l;
                o = k * n;
                totalSewaField.setText(String.valueOf(o));
                tahunField1.setText(String.valueOf(m) + "/" + bulanComboBox.getSelectedItem() + "/" + tahunField.getText());
            }
            rs.close();
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_generatePeminjamanBtnActionPerformed

    private void idPeminjamanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeminjamanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPeminjamanFieldActionPerformed

    private void idPelangganField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganField2ActionPerformed

    private void tahunFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunFieldActionPerformed

    private void sewaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaFieldActionPerformed

    private void tahunField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunField1ActionPerformed

    private void savePeminjamanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePeminjamanBtnActionPerformed
        // TODO add your handling code here:
        peminjaman pem = new peminjaman();
        pem.setPem(idPeminjamanField.getText());
        pem.setPel (idPelangganField.getText());
        pem.setMobil("" + jenisMobilComboBox.getSelectedItem());
        pem.setPtanggal(""+tanggalComboBox.getSelectedItem());
        pem.setPbulan(""+bulanComboBox.getSelectedItem());
        pem.setPtahun(tahunField.getText());
        pem.setKtahun(tahunField1.getText());
        pem.setLama(lamaField.getText());
        pem.setPegawai(idPegawaiField.getText());
        pem.setBiaya(sewaField.getText());

        pem.insertPeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");

        idPeminjamanField.setText(null);
        idPelangganField.setText(null);
        jenisMobilComboBox.setSelectedIndex(0);
        tanggalComboBox.setSelectedIndex(0);
        bulanComboBox.setSelectedIndex(0);
        tahunField.setText(null);
        tahunField1.setText(null);
        lamaField.setText(null);
        idPegawaiField.setText(null);
        sewaField.setText(null);
        totalSewaField.setText(null);
    }//GEN-LAST:event_savePeminjamanBtnActionPerformed

    private void idPeminjamanField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeminjamanField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPeminjamanField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        koneksi kon = new koneksi();
        ResultSet rs = null;
        try{
            rs = kon.getData("select *from t_peminjamanxxx where id_peminjaman ='"+idPeminjamanField1.getText()+"'");
            while(rs.next()){
                idPelangganField3.setText(rs.getString("id_pelanggan"));
                idMobilField3.setText(rs.getString("id_mobil"));
                tglPinjamField.setText(rs.getString("tgl_pinjam"));
                lamaPinjamField.setText(String.valueOf(rs.getInt("lama") ));
                biayaSewaField.setText(String.valueOf(rs.getInt("biaya" )));
                tglKembaliField.setText(rs.getString("tgl_hrs_kembali"));
            }
            rs.close();
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int k, l;
        k = Integer.valueOf(telatField.getText()).intValue();
        l = k * 100000;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        peminjaman pem = new peminjaman();
        pem.setPem(idPeminjamanField1.getText());
        pem.setTelat(telatField.getText());
        pem.setDenda(dendaField.getText());
        pem.updatePeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextArea alamatPelangganField;
    private javax.swing.JTextArea alamatPelangganField1;
    private javax.swing.JTextField biayaSewaField;
    private javax.swing.JComboBox<String> bulanComboBox;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelPeminjamanBtn;
    private javax.swing.JTextField cpPelangganField;
    private javax.swing.JTextField cpPelangganField1;
    private javax.swing.JPanel dataPelangganPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dendaField;
    private javax.swing.JButton generatePeminjamanBtn;
    private javax.swing.JTextField idMobilField3;
    private javax.swing.JTextField idPegawaiField;
    private javax.swing.JTextField idPelangganField;
    private javax.swing.JTextField idPelangganField1;
    private javax.swing.JTextField idPelangganField2;
    private javax.swing.JTextField idPelangganField3;
    private javax.swing.JTextField idPelangganSearchField;
    private javax.swing.JTextField idPeminjamanField;
    private javax.swing.JTextField idPeminjamanField1;
    private javax.swing.JPanel inputPelangganPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jenisMobilComboBox;
    private javax.swing.JTextField lamaField;
    private javax.swing.JTextField lamaPinjamField;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mobilPanel;
    private javax.swing.JTextField namaPelangganField;
    private javax.swing.JTextField namaPelangganField1;
    private javax.swing.JPanel peminjamanPanel;
    private javax.swing.JPanel pengembalianPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton savePeminjamanBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField sewaField;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField tahunField1;
    private javax.swing.JComboBox<String> tanggalComboBox;
    private javax.swing.JTextField telatField;
    private javax.swing.JTextField tglKembaliField;
    private javax.swing.JTextField tglPinjamField;
    private javax.swing.JTextField totalSewaField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
